import turtle
turtle.pendown()
turtle.left(90)


def square(x, y, length, line_color, filling_color):
    turtle.up()
    turtle.setposition(x, y)
    turtle.down()
    turtle.color(line_color, filling_color)
    turtle.begin_fill()
    turtle.forward(length)
    turtle.right(90)
    turtle.forward(length)
    turtle.right(90)
    turtle.forward(length)
    turtle.right(90)
    turtle.forward(length)
    turtle.right(90)
    turtle.end_fill()

def leg_triangle(x, y, leg_length, line_color, filling_color):
    turtle.up()
    turtle.setposition(x, y)
    turtle.down()
    turtle.color(line_color, filling_color)
    turtle.begin_fill()
    turtle.forward((2*leg_length**2)**0.5)
    turtle.right(135)
    turtle.forward(leg_length)
    turtle.right(90)
    turtle.forward(leg_length)
    turtle.right(135)
    turtle.end_fill()

def hypotenuse_triangle(x, y, hypotenuse_length, line_color, filling_color):
    turtle.up()
    turtle.setposition(x, y)
    turtle.down()
    turtle.color(line_color, filling_color)
    turtle.begin_fill()
    turtle.forward(hypotenuse_length)
    turtle.right(135)
    turtle.forward((0.5*hypotenuse_length**2)**0.5)
    turtle.right(90)
    turtle.forward((0.5*hypotenuse_length**2)**0.5)
    turtle.right(135)
    turtle.end_fill()

def parallelogram(x, y, length, height,  line_color, filling_color):
    turtle.up()
    turtle.setposition(x, y)
    turtle.down()
    turtle.color(line_color, filling_color)
    turtle.begin_fill()
    turtle.right(45)
    turtle.forward(height/((2**0.5)/2))
    turtle.right(45)
    turtle.forward(length)
    turtle.right(135)
    turtle.forward(height / ((2 ** 0.5) / 2))
    turtle.right(45)
    turtle.forward(length)
    turtle.right(45)
    turtle.end_fill()

def rectangle(x, y, length, height, line_color, filling_color):
    turtle.up()
    turtle.setposition(x, y)
    turtle.down()
    turtle.color(line_color, filling_color)
    turtle.begin_fill()
    turtle.forward(height)
    turtle.right(90)
    turtle.forward(length)
    turtle.right(90)
    turtle.forward(height)
    turtle.right(90)
    turtle.forward(length)
    turtle.right(90)
    turtle.end_fill()

turtle.done()

